const countries = [
  { cca2: "af", name: "Afghanistan", style: "mesh", },
  { cca2: "al", name: "Albania", style: "mesh", },
  { cca2: "dz", name: "Algeria", style: "mesh", },
  { cca2: "ad", name: "Andorra", style: "pin", },
  { cca2: "ao", name: "Angola", style: "mesh", },
  { cca2: "ar", name: "Argentina", style: "mesh", },
  { cca2: "am", name: "Armenia", style: "mesh", },
  { cca2: "au", name: "Australia", style: "mesh", },
  { cca2: "at", name: "Austria", style: "mesh", },
  { cca2: "az", name: "Azerbaijan", style: "mesh", },
  { cca2: "bs", name: "Bahamas", style: "mesh", },
  { cca2: "bh", name: "Bahrain", style: "pin", },
  { cca2: "bd", name: "Bangladesh", style: "mesh", },
  { cca2: "by", name: "Belarus", style: "mesh", },
  { cca2: "be", name: "Belgium", style: "mesh", },
  { cca2: "bz", name: "Belize", style: "mesh", },
  { cca2: "bj", name: "Benin", style: "mesh", },
  { cca2: "bt", name: "Bhutan", style: "mesh", },
  { cca2: "bo", name: "Bolivia", style: "mesh", },
  { cca2: "ba", name: "Bosnia and Herzegovina", style: "mesh", },
  { cca2: "bw", name: "Botswana", style: "mesh", },
  { cca2: "br", name: "Brazil", style: "mesh", },
  { cca2: "bn", name: "Brunei", style: "pin", },
  { cca2: "bg", name: "Bulgaria", style: "mesh", },
  { cca2: "bf", name: "Burkina Faso", style: "mesh", },
  { cca2: "bi", name: "Burundi", style: "mesh", },
  { cca2: "kh", name: "Cambodia", style: "mesh", },
  { cca2: "cm", name: "Cameroon", style: "mesh", },
  { cca2: "ca", name: "Canada", style: "mesh", },
  { cca2: "cv", name: "Cape Verde", style: "pin", },
  { cca2: "cf", name: "Central African Republic", style: "mesh", },
  { cca2: "td", name: "Chad", style: "mesh", },
  { cca2: "cl", name: "Chile", style: "mesh", },
  { cca2: "cn", name: "China", style: "mesh", },
  { cca2: "co", name: "Colombia", style: "mesh", },
  { cca2: "km", name: "Comoros", style: "pin", },
  { cca2: "cr", name: "Costa Rica", style: "mesh", },
  { cca2: "hr", name: "Croatia", style: "mesh", },
  { cca2: "cu", name: "Cuba", style: "mesh", meshMethod: "turf", },
  { cca2: "cy", name: "Cyprus", style: "pin", },
  { cca2: "cz", name: "Czechia", style: "mesh", },
  { cca2: "ci", name: "Cote dIvoire", style: "mesh", }, //todo fixme
  { cca2: "cd", name: "Democratic Republic of the Congo", style: "mesh", },
  { cca2: "dk", name: "Denmark", style: "mesh", },
  { cca2: "dj", name: "Djibouti", style: "mesh", },
  { cca2: "do", name: "Dominican Republic", style: "mesh", },
  { cca2: "ec", name: "Ecuador", style: "mesh", },
  { cca2: "eg", name: "Egypt", style: "mesh", },
  { cca2: "sv", name: "El Salvador", style: "mesh", },
  { cca2: "gq", name: "Equatorial Guinea", style: "mesh", },
  { cca2: "er", name: "Eritrea", style: "mesh", },
  { cca2: "ee", name: "Estonia", style: "mesh", },
  { cca2: "sz", name: "Eswatini", style: "mesh", },
  { cca2: "et", name: "Ethiopia", style: "mesh", },
  { cca2: "fj", name: "Fiji", style: "mesh", },
  { cca2: "fi", name: "Finland", style: "mesh", },
  { cca2: "fr", name: "France", style: "mesh", },
  { cca2: "ga", name: "Gabon", style: "mesh", },
  { cca2: "gm", name: "Gambia", style: "mesh", },
  { cca2: "ge", name: "Georgia", style: "mesh", },
  { cca2: "de", name: "Germany", style: "mesh", },
  { cca2: "gh", name: "Ghana", style: "mesh", },
  { cca2: "gr", name: "Greece", style: "mesh", },
  { cca2: "gt", name: "Guatemala", style: "mesh", },
  { cca2: "gn", name: "Guinea", style: "mesh", },
  { cca2: "gw", name: "Guinea-Bissau", style: "mesh", },
  { cca2: "gy", name: "Guyana", style: "mesh", },
  { cca2: "ht", name: "Haiti", style: "mesh", },
  { cca2: "hn", name: "Honduras", style: "mesh", },
  { cca2: "hu", name: "Hungary", style: "mesh", },
  { cca2: "is", name: "Iceland", style: "mesh", },
  { cca2: "in", name: "India", style: "mesh", elevation: "1.05" },
  { cca2: "id", name: "Indonesia", style: "mesh", },
  { cca2: "ir", name: "Iran", style: "mesh", },
  { cca2: "iq", name: "Iraq", style: "mesh", },
  { cca2: "ie", name: "Ireland", style: "mesh", },
  { cca2: "il", name: "Israel", style: "mesh", },
  { cca2: "it", name: "Italy", style: "mesh", },
  { cca2: "jm", name: "Jamaica", style: "mesh", },
  { cca2: "jp", name: "Japan", style: "mesh", },
  { cca2: "jo", name: "Jordan", style: "mesh", },
  { cca2: "kz", name: "Kazakhstan", style: "mesh", },
  { cca2: "ke", name: "Kenya", style: "mesh", },
  { cca2: "kw", name: "Kuwait", style: "mesh", },
  { cca2: "kg", name: "Kyrgyzstan", style: "mesh", },
  { cca2: "la", name: "Laos", style: "mesh", },
  { cca2: "lv", name: "Latvia", style: "mesh", },
  { cca2: "lb", name: "Lebanon", style: "mesh", },
  { cca2: "ls", name: "Lesotho", style: "mesh", },
  { cca2: "lr", name: "Liberia", style: "mesh", },
  { cca2: "ly", name: "Libya", style: "mesh", },
  { cca2: "li", name: "Liechtenstein", style: "pin", },
  { cca2: "lt", name: "Lithuania", style: "mesh", },
  { cca2: "lu", name: "Luxembourg", style: "pin", },
  { cca2: "mg", name: "Madagascar", style: "mesh", },
  { cca2: "mw", name: "Malawi", style: "mesh", },
  { cca2: "my", name: "Malaysia", style: "mesh", },
  { cca2: "mv", name: "Maldives", style: "pin", },
  { cca2: "ml", name: "Mali", style: "mesh", },
  { cca2: "mt", name: "Malta", style: "pin", },
  { cca2: "mr", name: "Mauritania", style: "mesh", },
  { cca2: "mu", name: "Mauritius", style: "pin", },
  { cca2: "mx", name: "Mexico", style: "mesh", },
  { cca2: "md", name: "Moldova", style: "mesh", },
  { cca2: "mc", name: "Monaco", style: "pin", },
  { cca2: "mn", name: "Mongolia", style: "mesh", },
  { cca2: "me", name: "Montenegro", style: "mesh", },
  { cca2: "ma", name: "Morocco", style: "mesh", },
  { cca2: "mz", name: "Mozambique", style: "mesh", },
  { cca2: "mm", name: "Myanmar", style: "mesh", },
  { cca2: "na", name: "Namibia", style: "mesh", },
  { cca2: "np", name: "Nepal", style: "mesh", },
  { cca2: "nl", name: "Netherlands", style: "mesh", },
  { cca2: "nz", name: "New Zealand", style: "mesh", meshMethod: "turf", },
  { cca2: "ni", name: "Nicaragua", style: "mesh", },
  { cca2: "ne", name: "Niger", style: "mesh", },
  { cca2: "ng", name: "Nigeria", style: "mesh", },
  { cca2: "kp", name: "North Korea", style: "mesh", },
  { cca2: "mk", name: "North Macedonia", style: "mesh", },
  { cca2: "no", name: "Norway", style: "mesh", meshMethod: "earcut", }, //TODo fixme
  { cca2: "om", name: "Oman", style: "mesh", },
  { cca2: "pk", name: "Pakistan", style: "mesh", },
  { cca2: "ps", name: "Palestine", style: "pin", },
  { cca2: "pa", name: "Panama", style: "mesh", },
  { cca2: "pg", name: "Papua New Guinea", style: "mesh", },
  { cca2: "py", name: "Paraguay", style: "mesh", },
  { cca2: "pe", name: "Peru", style: "mesh", },
  { cca2: "ph", name: "Philippines", style: "mesh", },
  { cca2: "pl", name: "Poland", style: "mesh", },
  { cca2: "pt", name: "Portugal", style: "mesh", },
  { cca2: "qa", name: "Qatar", style: "mesh", },
  { cca2: "cg", name: "Republic of the Congo", style: "mesh", },
  { cca2: "ro", name: "Romania", style: "mesh", },
  { cca2: "ru", name: "Russia", style: "mesh", },
  { cca2: "rw", name: "Rwanda", style: "mesh", },
  { cca2: "sm", name: "San Marino", style: "pin", },
  { cca2: "sa", name: "Saudi Arabia", style: "mesh", },
  { cca2: "sn", name: "Senegal", style: "mesh", },
  { cca2: "rs", name: "Serbia", style: "mesh", },
  { cca2: "sc", name: "Seychelles", style: "pin", },
  { cca2: "sl", name: "Sierra Leone", style: "mesh", },
  { cca2: "sg", name: "Singapore", style: "pin", },
  { cca2: "sk", name: "Slovakia", style: "mesh", },
  { cca2: "si", name: "Slovenia", style: "mesh", },
  { cca2: "sb", name: "Solomon Islands", style: "mesh", },
  { cca2: "so", name: "Somalia", style: "mesh", },
  { cca2: "za", name: "South Africa", style: "mesh", },
  { cca2: "kr", name: "South Korea", style: "mesh", },
  { cca2: "ss", name: "South Sudan", style: "mesh", },
  { cca2: "es", name: "Spain", style: "mesh", },
  { cca2: "lk", name: "Sri Lanka", style: "mesh", },
  { cca2: "sd", name: "Sudan", style: "mesh", },
  { cca2: "sr", name: "Suriname", style: "mesh", },
  { cca2: "se", name: "Sweden", style: "mesh", },
  { cca2: "ch", name: "Switzerland", style: "mesh", },
  { cca2: "sy", name: "Syria", style: "mesh", },
  { cca2: "tj", name: "Tajikistan", style: "mesh", },
  { cca2: "tz", name: "Tanzania", style: "mesh", },
  { cca2: "th", name: "Thailand", style: "mesh", },
  { cca2: "tl", name: "Timor-Leste", style: "mesh", },
  { cca2: "tg", name: "Togo", style: "mesh", },
  { cca2: "tn", name: "Tunisia", style: "mesh", },
  { cca2: "tr", name: "Turkey", style: "mesh", },
  { cca2: "tm", name: "Turkmenistan", style: "mesh", },
  { cca2: "ug", name: "Uganda", style: "mesh", },
  { cca2: "ua", name: "Ukraine", style: "mesh", },
  { cca2: "ae", name: "United Arab Emirates", style: "mesh", },
  { cca2: "gb", name: "United Kingdom", style: "mesh", },
  { cca2: "us", name: "United States", style: "mesh", },
  { cca2: "uy", name: "Uruguay", style: "mesh", },
  { cca2: "uz", name: "Uzbekistan", style: "mesh", },
  { cca2: "va", name: "Vatican City", style: "pin", },
  { cca2: "ve", name: "Venezuela", style: "mesh", },
  { cca2: "vn", name: "Vietnam", style: "mesh", },
  { cca2: "ye", name: "Yemen", style: "mesh", },
  { cca2: "zm", name: "Zambia", style: "mesh", },
  { cca2: "zw", name: "Zimbabwe", style: "mesh", },
  { cca2: "vu", name: "Vanuatu", style: "mesh", },
  { cca2: "tv", name: "Tuvalu", style: "pin", },
  { cca2: "to", name: "Tonga", style: "pin", },
  { cca2: "tt", name: "Trinidad and Tobago", style: "pin", },
  { cca2: "st", name: "Sao Tome and Principe", style: "pin", },
  { cca2: "kn", name: "Saint Kitts and Nevis", style: "pin", },
  { cca2: "lc", name: "Saint Lucia", style: "pin", },
  { cca2: "vc", name: "Saint Vincent and the Grenadines", style: "pin", },
  { cca2: "ws", name: "Samoa", style: "pin", },
  { cca2: "pw", name: "Palau", style: "pin", },
  { cca2: "ki", name: "Kiribati", style: "pin", },
  { cca2: "nr", name: "Nauru", style: "pin", },
  { cca2: "mh", name: "Marshall Islands", style: "pin", },
  { cca2: "fm", name: "Micronesia", style: "pin", },
  { cca2: "dm", name: "Dominica", style: "pin", },
  { cca2: "gd", name: "Grenada", style: "pin", },
  { cca2: "ag", name: "Antigua and Barbuda", style: "pin", },
  { cca2: "bb", name: "Barbados", style: "pin", },
];

export { countries }